# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: lint.yaml

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: quay.io/nexomis/r-nexoverse:4.4.2-01.25
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          Rscript install.r requirements.txt
          Rscript install.r requirements.dev.txt
        working-directory: .devcontainer/
      - name: Lint
        run: Rscript .dev/scripts/lint_package.R
      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: lintr_results.sarif
          category: lintr
